### ISSUE TITLE
Add interface for current measurment

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch-Dock#27]
Add a 2-pin jumper for a current measurement of the watch. A PPK2 can use this interface.

**Comment by jakkra** [comment]
Question is if this would show correct readings. Charger can be disabled in SW, but vbus will turn on USB switch. But may still be good for hunting stuff that consumes more than a few uA

**Comment by Kampi** [comment]
> Question is if this would show correct readings. Charger can be disabled in SW, but vbus will turn on USB switch. But may still be good for hunting stuff that consumes more than a few uA

That´s true. The USB switch will consume the same amount of power all the time so you have a small offset. IMO it can make sense because otherwise you have to open the watch again and again to measure directly at the battery connector.

**Comment by jakkra** [comment]
Yes I agree it still makes sense and is useful
